"""changing through table in Group & channel models and adding joines_at field to them

Revision ID: f5c4f090ccff
Revises: f671bda11da9
Create Date: 2025-11-01 00:00:11.114550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c4f090ccff'
down_revision: Union[str, Sequence[str], None] = 'f671bda11da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_user', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('channel_user', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channel_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('group_user', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('group_user', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_user', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('group_user', 'joined_at')
    op.alter_column('channel_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channel_user', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('channel_user', 'joined_at')
    # ### end Alembic commands ###
